### ISSUE TITLE
AsyncAction sucess assumes payload.result

### ISSUE THREAD

**Issue by bakesteve** [aikoven/typescript-fsa#11]
Trying to use this, but my async actions will return the result type as the payload, rather than under `action.payload.result`
When I use `isType(action, someaction.done)` payload is now typed to be `ActionCreator<Success<P, S>>` so according to typescript, I need to grab the actual api result from `action.payload.result`
I'm using middleware, so cant easily change this just for the files I am using this on. is there a way round this?

**Comment by aikoven** [comment]
This means that your async actions have different type than `AsyncActionCreators`  in this lib, but you can easily write your own, it's quite simple: https://github.com/aikoven/redux-typescript-actions/blob/v1.2.0/src/index.ts#L105-L114

**Comment by aikoven** [comment]
I'm going to close this, please feel free to reopen if you have any questions.
