### ISSUE TITLE
Rename package

### ISSUE THREAD

**Issue by farism** [aikoven/typescript-fsa#12]
I think it might be good to rename this package to `typescript-fsa` or `fsa-typescript` or something along those lines. This library can technically be used with any FSA compliant flux implementation, or even something else. For example I am currently using it in a cycle.js project. 

On top of this, the redux dependency probably isn't necessary. We could reimplement the `ReduxAction` type in this library and be fairly certain that the API won't change as FSA is a pretty concrete interface at this point in time.

Also if you haven't seen it, should take a look at https://github.com/UrbanDoor/typed-fsa. Seems there are similar goals for both of these projects. Though I prefer this library's `isType` check over that other library's `isAction` check for narrowing, as there is no need to declare the payload again.

Thanks for all the hard work!

**Comment by aikoven** [comment]
Thanks for your input and thanks for sharing `typed-fsa`, I haven't seen it before.

You are right in that Redux dependency is not really needed, though I've planned to include some utilities for building reducers which might depend on Redux. There's already [a module](https://github.com/aikoven/redux-typescript-actions/blob/v1.3.0/src/sagas.ts) with helpers for `redux-saga`. However, this module is not imported from `index.ts` and `redux-saga` is listed as optional dependency.

In general I like the idea of decoupling from Redux, but that means that we'd have to publish helpers as separate packages, like `typescript-fsa-redux-saga`. Still, I guess this should be done anyway.

**Comment by farism** [comment]
Admittedly I wasn't thinking about the saga aspect when I was first opened this issue 😄. Though it doesn't change my gut instinct.

At the very least I think it would be good to remove the `redux` dependency and reimplement the base `Action` interface. We could discuss possible options for helpers.

**Comment by aikoven** [comment]
Just released [`typescript-fsa@2.0.0`](https://www.npmjs.com/package/typescript-fsa).

**Comment by farism** [comment]
Very cool, will try it out this weekend.

**Comment by farism** [comment]
I migrated to new package and my app seems to be working well. I think we can close this one out. Nice work!
