### ISSUE TITLE
Consider typescript-fsa-reducers for Companion Packages section

### ISSUE THREAD

**Issue by dphilipson** [aikoven/typescript-fsa#18]
Hello, I'm a big fan of this library. Thank you for creating it!

I've written a package, [typescript-fsa-reducers](https://github.com/dphilipson/typescript-fsa-reducers), which builds on top of typescript-fsa to simplify writing reducers. I wanted to bring it to your attention in case you're interested in adding it to the "Companion Packages" section of your README. If not, no hard feelings, and thanks again for the work you've done.

**Comment by ttamminen** [comment]
@dphilipson typescript-fsa-reducers looks interesting indeed and should be mentioned some place more visible than inside an issue!

I think the TypeScript FSA project should have some sort of Resources section. Not only for Companion Packages, such as great reducers library by David, but learning resources also.

For example, I have written some tutorials like [Type-safe Flux Standard Actions (FSA) in React Using TypeScript FSA](https://www.triplet.fi/blog/type-safe-flux-standard-actions-fsa-in-react-using-typescript-fsa/) that developers new to the project might find useful.

**Comment by aikoven** [comment]
Thanks, I'd be happy to include it. Would you mind opening a PR for the Readme?

**Comment by dphilipson** [comment]
PR created: https://github.com/aikoven/typescript-fsa/pull/20

@ttamminen You'll want to open a separate PR to add links to your tutorials.
