### ISSUE TITLE
Change definition of meta?

### ISSUE THREAD

**Issue by mindjuice** [aikoven/typescript-fsa#26]
When I try to set a field on `meta`, TypeScript complains that the property does not exist.

For example:

```
myAction.meta.requestId = 123

>> Property 'requestId' does not exist on type 'Object'.
```

The current definition of `meta` in `Action<P>` looks like this:

```
  meta?: Object | null;
```

If I change it as follows, then I can place any fields into `meta` with no errors.

```
  meta?: { [x: string]: any } | null;
```

Of course this means `meta` is not type-safe, but it's no worse than the current definition.

Another alternative would be to provide a type parameter for `meta` (e.g., `Action<P,M>`), but that might be a bit of overkill for a field like `meta`.

Any interest in either of these changes?

**Comment by aikoven** [comment]
Why do you want to change the meta after your action is created in the first place? I'd rather perceive actions as read-only.

Otherwise, your proposal looks good, I'll update the types and open a PR so you could check if it works for you.

**Comment by aikoven** [comment]
Please check out version `2.3.0`.

**Comment by mindjuice** [comment]
In this case I was looking at having middleware add a `requestId` and a `startTime` to the action when it is received by the middleware then sent over the websocket, but I may use a map on `requestId` as a key instead to keep the actions read only.

Either way, `2.3.0` looks great.  Thanks!
