### ISSUE TITLE
Question about `done` and `failed` action creators

### ISSUE THREAD

**Issue by ssynix** [aikoven/typescript-fsa#29]
Is there a way to skip params in async action results? Something like:
```ts
    done: ActionCreator<S>;
    failed: ActionCreator<E>;
```
___
Let's say I want to fetch all users. This is kind of what I expected: (pseudocode)
```ts
dispatch fetchingAllUsers.started();
// do the fetching
if (error) {
    fetchingAllUsers.failed({ error: error.message });
} else {
    fetchingAllUsers.done({ users: users[] });
}
```
___
I'm mostly new to all this so I was wondering if I'm missing something or if there's a better way to utilize this library.

Thanks!

**Comment by aikoven** [comment]
Async action creators are meant to wrap async processes, like a network request. The `params` are needed to correlate the response with the request arguments. Imagine that you're making many similar requests through a single AAC.

The most convenient way for using AAC is to make a wrapper based on how you do async stuff in your project. 

Here's a ready to use wrapper for `redux-saga`: https://github.com/aikoven/typescript-fsa-redux-saga

There is also a discussion on integrating AACs with `redux-thunk`: https://github.com/aikoven/typescript-fsa/issues/19

**Comment by ssynix** [comment]
Thanks for the explanation! In your `redux-saga` example, how does `mySaga` get triggered in the first place? Do I need to take a `startDoSomething` action? E.g.

1. Component wants list of users
1. Dispatch `startFetchingUsers`
1. Outer saga (`mySaga`) takes this action and calls the `boundAsyncAction` saga
1. `fetchingUsers.started/done/failed` are dispatched respectively

I really like the idea of automatically dispatching actions throughout the lifecycle of a saga, but to me it seems like steps 2-3 are a bit redundant. So in my case I'd want to dispatch `fetchingUsers.start`, and then have the bound saga take it and report the results through `.done/failed`

Would you mind clarifying this for me as well? Thanks again!

**Comment by aikoven** [comment]
The `AAC.started` action is not something that triggers an async process, more like an *event* that happens once the process is started.

So once you've bound your process with `bindAsyncAction` you get the same thing but wrapped with actions. You execute it just like you would have done with the original process (with `yield call(...)`).

To wire it up with the component I'd do this: once a component is mounted, dispatch an action `SOME_COMPONENT_MOUNTED`. Then use `takeEvery`/`takeLatest` in the saga to start the process.

I recommend keeping actions as dumb as possible, without any notion of what will happen in your app once they're dispatched. If a user clicks a button somewhere, just dispatch `SOME_BUTTON_CLICKED`. This greatly decouples components from the logic which is spread between reducers and sagas.

**Comment by ssynix** [comment]
Great tips, thank you!
