### ISSUE TITLE
Use case for isType looser type on actionCreator parameter maybe ?

### ISSUE THREAD

**Issue by rluiten** [aikoven/typescript-fsa#35]
Love your work, so much nicer to have good types.
I've been using it with the typescript-fsa-redux-thunk wrapper bindActionThunk().

I have a use case at the moment where I am creating `myIsType` based on isType.
The function prototype on the `actionCreator` parameter gives type errors.
I was wondering if the type for that parameter on isType might be loosened without risk ?

`pendingAsyncActions` is just an array of all the action async api creators that I care to keep track of pending activity in the application.

I still feel a bit of depth with complexities of typscripts types and interpretting its error messages I tried to create a more restrictive type for myIsType than `any` but quickly got complex type messages that defeated me.

```typescript
const myIsType = isType as any;

export default function pendingCountReducer(
  count: State = InitialState,
  action: AnyAction
) {
  pendingAsyncActions.forEach(apiAction => {
    if (isType(action, apiAction.started)) {
      count = count + 1;
    } else if (
      isType(action, apiAction.failed) ||
      myIsType(action, apiAction.done)
    ) {
      count = count - 1;
    }
  });
  return count;
}
```

**Comment by aikoven** [comment]
Sorry for the late reply.

What exact error do you get from TS?

**Comment by rluiten** [comment]
For the example i posted above on the line where `myIsType` is used, the second parameter apiAction.done gives me an error.



```
ERROR in [at-loader] ./src/reducers/pendingCountReducer.ts:27:22
    TS2345: Argument of type 'ActionCreator<Success<GetConfigParams, IConfigModel>> | ActionCreator<Success<GetObservationsPara...' is not assignable to parameter of type 'ActionCreator<Success<GetConfigParams, IConfigModel>>'.
  Type 'ActionCreator<Success<GetObservationsParams, IObservationViewModel[]>>' is not assignable to type 'ActionCreator<Success<GetConfigParams, IConfigModel>>'.
    Type 'Success<GetObservationsParams, IObservationViewModel[]>' is not assignable to type 'Success<GetConfigParams, IConfigModel>'.
      Type 'IObservationViewModel[]' is not assignable to type 'IConfigModel'.
        Property 'apiUrls' is missing in type 'IObservationViewModel[]'.
```

The array pendingAsyncActions is defined as.
The result type for each async action creator is different as you would expect in general.
I read the error as being caused because in the `done` case the type of payload is different, I was thinking maybe there is a way to make isType not a full ActionCreator<P> but only require the field type on the second parameter and not the function signature.

```typescript
export const getConfig = actionCreator.async<
  RootState,
  GetConfigParams,
  Vm.IConfigModel,
  Error
>('GET_CONFIG');

export const getObservations = actionCreator.async<
  RootState,
  GetObservationsParams,
  Vm.IObservationViewModel[],
  Error
>('GET_OBSERVATIONS');

export const pendingAsyncActions = [
  getConfig,
  getObservations,
];


```

**Comment by aikoven** [comment]
I'm confused.

`isType` doesn't  make any restriction on `P` type parameter, and I don't see how it can produce an error you posted.

Could you make a small repo that reproduces it, so I could have a closer look?

**Comment by rluiten** [comment]
Sorry for the delay, was finishing up some other urgent stuff.

I created a file to demonstrate the error.
I can upload a repo if you would prefer that.

* install create-react-app
* create a project
  * create-react-app cra-istype --scripts-version=react-scripts-ts
* install typescript-fsa
  * npm install --save typescript-fsa
* place file the attached file typeExample.ts.txt in to src folder with name typeExample.ts
* include typeExample.ts into App.tsx with following line
  * import './typeExample';

* start dev mode with `npm start`

See error as follows
```
Failed to compile
./src/typeExample.ts
(47,22): error TS2345: Argument of type 'ActionCreator<Success<Type2Params, Type2Result>> | ActionCreator<Success<Type1Params, Type1Result>>' is not assignable to parameter of type 'ActionCreator<Success<Type2Params, Type2Result>>'.
  Type 'ActionCreator<Success<Type1Params, Type1Result>>' is not assignable to type 'ActionCreator<Success<Type2Params, Type2Result>>'.
    Type 'Success<Type1Params, Type1Result>' is not assignable to type 'Success<Type2Params, Type2Result>'.
      Type 'Type1Result' is not assignable to type 'Type2Result'.
        Property 'result1Id' is missing in type 'Type1Result'.
This error occurred during the build time and cannot be dismissed.
```
[typeExample.ts.txt](https://github.com/aikoven/typescript-fsa/files/1223788/typeExample.ts.txt)

**Comment by aikoven** [comment]
The error happens because the type of `pendingAsyncActions` is inferred to
```ts
(AsyncActionCreators<Type1Params, Type1Result, Error> | 
 AsyncActionCreators<Type2Params, Type2Result, Error>)[]
```
which in turn makes `apiAction.done` be inferred to
```ts
ActionCreator<Success<Type1Params, Type1Result>> |
ActionCreator<Success<Type2Params, Type2Result>> 
```
TypeScript is not smart enough to see that this is the same as
```ts
ActionCreator<Success<Type1Params | Type2Params, Type1Result | Type2Result>>
```

Also, the reason you get the error only for `done` action is that `Type1Params` is exactly the same as `Type2Params`.

I see two possible fixes:
1. Annotate `pendingAsyncActions` with `AsyncActionCreators<any, any, any>[]` type.
2. Annotate `apiAction` with `AsyncActionCreators<any, any, any>` type.

**Comment by rluiten** [comment]
As i expected. I  was just wondering if it was possible to ease of the type constraints in isType() but I have learned more since then and I don't think its feasible as it wont enforce the type guard if you did.

Thanks for the detailed response.
