### ISSUE TITLE
Is typescript-fsa compatible with ngrx 4?

### ISSUE THREAD

**Issue by st-clair-clarke** [aikoven/typescript-fsa#40]
Given the changes with ngrx 4, is typescript-fsa still compatible? There are changes with Actions (for example, there is no payload property). How does this impact on this package? 

See migration guide at [https://github.com/ngrx/platform/blob/master/MIGRATION.md](https://github.com/ngrx/platform/blob/master/MIGRATION.md)

Thanks

**Comment by aikoven** [comment]
I'm not using ngrx, so I can't say with confidence. I think that everything should work fine. `typescript-fsa` makes little assumption on what actions should be (see `AnyAction` type). It should integrate flawlessly with any Flux implementation that relies on actions having `type` property.

**Comment by matthewharwood** [comment]
I had a problem with how verbose ngrx4 was.  I posted a question on stackoverflow and proded the gitter community and they lead me to typescript-fsa.

Once I get more infomation and time to test.  I think it would be great to have a few snippet on implementation for beginners.

https://stackoverflow.com/questions/46823049/how-can-i-refactor-ngrx-actions-to-be-less-prone-to-typos

**Comment by baetheus** [comment]
I implemented it today and it works just fine. typescript-fsa-reducers are also quite useful.

**Comment by aikoven** [comment]
I'm going to close this since the issue seems to be resolved. Please feel free to reopen if you have any trouble.
