### ISSUE TITLE
Provide a simple example of how to use both regular and async action in combination with connect

### ISSUE THREAD

**Issue by tcoopman** [aikoven/typescript-fsa#5]
I'm struggling with getting the props interface correct, especially for async actions. It would be nice if there were a simple example, showing define the actions in a connected component.

**Comment by aikoven** [comment]
Not sure if I understand.

Defining and dispatching actions:
```tsx
// actions.ts
const actionCreator = actionCreatorFactory();

// {foo: string} is the payload type
export const buttonClicked = actionCreator<{foo: string}>('BUTTON_CLICKED');

// Component.ts
connect(
  state => ...,
  dispatch => {
    return {
      handleButtonClick() {
        dispatch(buttonClicked({foo: 'bar'});
      }
    };
  }
)(props => {
  return <button onClick={props.handleButtonClick}/>;
})
```

Async action creators are not meant to be directly used by component, but rather to wrap some async process. Here's an example of usage with Promises and `redux-thunk`:

```ts
function wrapAsyncWorker<P, R>(
  asyncAction: AsyncActionCreators<P, R>,
  worker: (params: P) => Promise<R>
) {
  return function wrappedWorker(dispatch, params: P): Promise<R> {
    dispatch(asyncAction.started(params));
    return worker(params).then(result => {
      dispatch(asyncAction.done({params, result}));
      return result;
    }, error => {
      dispatch(asyncAction.failed({params, error});
      throw error;
    });
  }
}

// actions.ts
// {foo: string} is params type, {bar: number} is result type
export const doSomething = actionCreator.async<{foo: string}, {bar: number}>('DO_SOMETHING');

const worker = wrapAsyncWorker(doSomething, params => {
  // do some async stuff, return a promise that resolves to {bar: number}
})

// thunk action creator
export const buttonClicked = (foo: string, bar: number) => {
  return dispatch => worker(dispatch, {foo, bar});
}
```

Maybe I should include this `wrapAsyncWorker` helper to the library.
I personally use `redux-saga` for all the async stuff, and have similar helper to wrap sagas with async actions.

**Comment by supermoos** [comment]
I would also like further examples on how to use it in conjunction with react-redux connect().

I have a piece of code here that hopefully explains what I wanna achieve:

It works the way it is written now, but the action isn't mapped with connect(), and thus HMR doesn't work. Ideally I would also like to avoid having to write the IUserProps type and just have it be inferred.

```
import * as React from 'react';
import {FormGroup, ControlLabel, FormControl, Checkbox} from 'react-bootstrap';
import {minLength} from '../../utils/ValidationUtils';
import {connect} from 'react-redux';
import {updateUser} from '../../redux/modules/user';
import {IStore} from '../../redux/IStore';
import {IUserProps} from '../../models/IUser';
const s = require('./BasicsForm.css');

class BasicsForm extends React.Component<IUserProps, void> {
    constructor(props:any) {
        super(props);
        this.handleChange = this.handleChange.bind(this);
        this.submitForm = this.submitForm.bind(this);
    }

    private handleChange(event):void {
        let value = event.target.value as string;
        this.props.dispatch(updateUser({user: {firstName: value}}));
        // this.props.updateUser({firstName: value});
    }

    private submitForm():void {
        // TODO: implement
        // this.props.updateUser({firstName: this.state.firstName});
    }

    public render() {
        return (
            <form className={s.basicsForm} onSubmit={this.submitForm}>
                <h3>Your basic information</h3>
                <FormGroup controlId="fname" validationState={minLength(this.props.firstName)}>
                    <ControlLabel>First Name *</ControlLabel>
                    <FormControl type="text" placeholder="First Name 2"
                                 value={this.props.firstName || ''}
                                 onChange={this.handleChange}
                    />
                </FormGroup>
                <input type="submit" value="Submit"/>
            </form>
        );
    }
}

// Wire up the React component to the Redux store
export default connect(
    (state:IStore) => state.user
)(BasicsForm);

/*
// This is the recommended way of using connect(), but how can you get type-awareness of the updateUser-function in this.props.updateUser() (see line: 20)
export default connect(
    (state:IStore) => state.user, // Selects which state properties are merged into the component's props
    (dispatch) => ({ // Selects which action creators are merged into the component's props
        updateUser: (user:IUser) => dispatch(updateUser({user}))
    })
)(BasicsForm);*/
```
IUser.ts
```
export interface IReduxActionDispatch {
    dispatch?:Function;
}

export interface IUser {
    readonly firstName?:string|null;
    readonly middleName?:string;
    readonly lastName?:string;
    readonly email?:string;
    readonly password?:string;
    readonly birthDate?:Date;
    readonly addressOne?:string;
    readonly addressTwo?:string;
    readonly gender?:'male'|'female'|'other';
    readonly maidenName?:string;
    readonly phone?:string;
    readonly country?:string;
    readonly city?:string;
    readonly state?:string;
    readonly zipCode?:number;
    readonly idVerified?:boolean;
}

export type IUserProps = IUser & IReduxActionDispatch;
```
Thanks for the effort!!

**Comment by aikoven** [comment]
@supermoos Sorry for the delay. 

I don't fully understand what's the problem with the code you've provided. Is it about this library or about using `react-redux` with TypeScript conveniently? In the latter case, I usually use the pattern that you can see in my first comment in this thread, namely:
```ts
const ConnectedComponent = connect(
  (state) => ...
  (dispatch) => ...
)(props => {
  // here `props` type will be inferred as intersection type of state props and dispatch 
  // props, i. e. an object that gets all properties from both.
});
```

I don't know any way of using the same with class components, because you have to always specify type parameters for generic classes, so e.g. this won't work:
```ts
const ConnectedComponent = connect(
  (state) => ...
  (dispatch) => ...
)(class extends Component {
});
```
So in this case you have to write another interface for `Component`'s props.

I personally rarely use class components in favor of stateless functional ones, almost always it is something that needs lifecycle hooks or working with the DOM, so they are mostly low-level UI stuff. There are literally no cases in my code where I'd need to `connect` such components.

**Comment by MartinMajewski** [comment]
But how do you nest your pattern inside a parent TSX (JSX) DOM element?
I don't get, how a complete application should look like.

Can you please provide a full example, please? For example an app that composes different separated input elements with some output elements, like buttons, checkboxes that changes a text inside label output.

Thank you.

**Comment by MistyKuu** [comment]
@aikoven can you please share wrapper async worker for redux-saga?

**Comment by aikoven** [comment]
@MartinMajewski I'll write an example when I have time. The basic usage has no difference with regular action creators. See [Redux manual](http://redux.js.org/docs/basics/Actions.html#action-creators).

@MistyKuu Here you go:
```ts
import {SagaIterator} from "redux-saga";
import {put, call, cancelled} from "redux-saga/effects";
import {AsyncActionCreators} from "redux-typescript-actions";

function bindAsyncAction<P, R>(
  actionCreators: AsyncActionCreators<P, R, any>,
  worker: (params: P) => Promise<R> | SagaIterator,
) {
  return function* boundAsyncActionSaga(params: P): SagaIterator {
    yield put(actionCreators.started(params));

    let result: R;
    let isCancelled = false;

    try {
      result = yield call(worker, params);
    } catch (error) {
      yield put(actionCreators.failed({params, error}));
      throw error;
    } finally {
      if (yield cancelled()) {
        isCancelled = true;
        yield put(actionCreators.failed({params, error: 'cancelled'}));
      }
    }

    if (!isCancelled)
      yield put(actionCreators.done({params, result}));

    return result;
  };
}
```
Usage:
```ts
const doSomething = actionCreator.async<{foo: number}, {bar: string}>('DO_SOMETHING');

// wrap worker with actions
const doSomethingWorker = bindAsyncAction(
  doSomething, 
  function* (params: {foo: number}): SagaIterator {
    // do some async stuff...
    return {bar: 'baz'};
  } 
);

function* someSaga(): SagaIterator {
  yield call(doSomethingWorker, {foo: 42});
}
```

**Comment by MistyKuu** [comment]
Thanks, I'll check that out

**Comment by aikoven** [comment]
@MistyKuu Sorry, I've completely missed your edit.

1. Yep, it should work exactly like this. Once https://github.com/redux-saga/redux-saga/pull/733 gets released, I'll update the library so that you could leave out `.type`:
```ts
yield takeEvery(actions.requestJobStarted, ...)
```
2. Sagas are intended to be run as daemons, so the basic workflow is this: your component dispatches simple plain action, saga catches it and executes some workflow. Please refer to redux-saga documentation for more info.

**Comment by QuantumInformation** [comment]
I think it would be nice to include that code in the library, saves confusion as to where it came from. (I discovered it in a repo im working on)

**Comment by QuantumInformation** [comment]
I've inherited a code base that uses this and https://github.com/dphilipson/typescript-fsa-reducers.

I'm seeing this issue:

<img width="864" alt="Screenshot 2019-03-12 at 15 51 02" src="https://user-images.githubusercontent.com/216566/54214745-b6b11d80-44de-11e9-9016-2461258f7d29.png">

Which stems from this file:


Is there something I can do to quickly fix this?

```js
import { Site } from '../../model/Site';
import { loadSites as eventApiLoadSites } from '../../rest-api/Event-api';
import { Dispatch } from 'redux';
import { actionCreatorFactory, AnyAction } from 'typescript-fsa';
import wrapAsyncWorker from './wrapAsyncWorker';

const actionCreator = actionCreatorFactory();

export const LoadSites = actionCreator.async<null, Site[]>('LoadSites');

const loadSitesWorker =
  wrapAsyncWorker(LoadSites, (): Promise<Site[]> => eventApiLoadSites());

export const loadSites = () => {
  return (dispatch: Dispatch<AnyAction>) => loadSitesWorker(dispatch, null);
};
```

**Comment by QuantumInformation** [comment]
I've rolled back some libraries, I noticed that typescript is looking at different node modules, the error goes away when the dispatch method looks likes this when I ctrl-click on `dispatch`

file"

```js
declare module "redux" {
  export interface Dispatch<S> {
    <R, E>(asyncAction: ThunkAction<R, S, E>): R;
  }
}
```
but on the latest version of the project I get the error when I ctrl-click on `dispatch` is from the file `node_modules/redux/index.d.ts`
`  dispatch: Dispatch<A>`

**Comment by QuantumInformation** [comment]
moved discussion here

https://github.com/aikoven/typescript-fsa/issues/72#issue-420408841
