### ISSUE TITLE
Amazing project, thank you! 🎉 

### ISSUE THREAD

**Issue by oieduardorabelo** [aikoven/typescript-fsa#53]
Hello there 👋,

I would like to thank your for this project and your time invested in this project,

I just rewrote a project in TS and I was handling everything with Enums and custom utilities, 

Looking for good patterns, I landed in this repo, all the `*-fsa-*` packages are awesome!

The code looks more tidy and organized!

Many thanks 🙏

**Comment by aikoven** [comment]
Thank you, Eduardo, that means a lot to me!
