### ISSUE TITLE
Make ActionCreatorFactory.async return an additional 'reset' action creator

### ISSUE THREAD

**Issue by IIFE** [aikoven/typescript-fsa#66]
Hi,

Firstly thanks for the library, it's proved very useful for me.

I just wanted to provide a small suggestion and get your thoughts on it.

One of the useful functions in `ActionCreatorFactory` is:
`async<P, S, E>(type: string, commonMeta?: Meta): AsyncActionCreators<P, S, E>;`

Which creates `started, done, failed` action creators. Would it not also be useful if it was to create a `reset` action creator that allows us to handle a reset action for resetting the async operation state to the initial one. I can create one manually, but I thought it would be nicer if the current function did that alongside the other action creators.

A `reset` action creator can become useful in the following scenario. I have the following state for an API operation:
```
interface IAPIOperation {
  pending: boolean;
  success: boolean;
  failure: boolean;
}
```
When I receive `started`, I set `IAPIOperation.pending` to `true`, and when I receive `done`, I set `IAPIOperation.success` to `true`, etc.

In my React container I watch for `IAPIOperation.success` to be `true`, and when it is, I redirect to another page. The issue is if I visit the page for that container again, it will detect that `IAPIOperation.success` is still `true`, and keep redirecting me. A reset would prevent that. Unless there is a nicer way of preventing that without the need for a reset.

Thanks

**Comment by aikoven** [comment]
I think what you're trying to achieve is better done at reducer side, not actions.

So imagine you have a reducer for your page's state. It's composed of some smaller ones, among which is the operation state (`IAPIOperation`):

```ts
const pageReducer = combineReducers({
  someOperation: operationReducer,
  // some other sub-states  
});
```

It actually makes sense to completely reset the page state when you leave it, not the particular parts of it. So I would go with something like:

```ts
const pageReducer = combineReducers({
  someOperation: operationReducer,
  // some other sub-states  
});

const finalStateReducer = (state, action) => {
  if (/* action is the page change */) {
    // reset state
    return pageReducer(undefined, action);
  }

  return pageReducer(state, action);
};
```

**Comment by aikoven** [comment]
I'm going to close this, please feel free to reopen.
