### ISSUE TITLE
Optional parameters not respected in 3.0.0

### ISSUE THREAD

**Issue by anodynos** [aikoven/typescript-fsa#79]
When I upgrade from `3.0.0-beta-2` to `3.0.0` I'm getting loads of 

`error TS2554: Expected 1-2 arguments but got 0.` 

for all my `actionFactory<void>` & `actionFactory.async<void, SomeType>`.

Reverting back to `3.0.0-beta-2` solves it. I'm on TypeScript 3.1.6.

**Comment by aikoven** [comment]
Can you please provide some code to reproduce?

**Comment by anodynos** [comment]
Sorry I've missed that, was bust/holidays :-)
I will do when I find some time next week...

**Comment by anodynos** [comment]
Closing this - I can't reproduce it any more (we've upgraded to TypeScript 3.5.3 since, maybe that has solved it, not sure ;-) )

Thanks for the lib, it rocks ;-)
